#include "k2_client/BodyArray.h"
#include "ros/ros.h"
#include <vector>
#include <string>
#include "std_msgs/String.h"



void bodies_sub_cb(const k2_client::BodyArray msg)
{
  
    
   //gjenkjenne gesturer fra kinnect:
    
  for (const auto& body : msg.bodies){
      
    //Ser om personen er glad
      
    if (body.expressions.happy){
        
      ROS_INFO("The user eats happymeal ");
        
    }
      
    //Ser om personen er nøytral
      
    else if (body.expressions.neutral){
        
      ROS_INFO("The user is neutral ");
        
    }
    //Ser om personen har øynene lukket
      
    if(body.activities.eyeleftClosed and body.activities.eyeRightClosed){
        
      ROS_INFO("Eye closed af");
        
    }
    //ser om personen har på seg briller
      
    if(body.appearance.wearingGlasses){
        
      ROS_INFO("Wearing Glases");
        
    }
      
  }

}




int main(int argc, char **argv)
{
    
  /  ros::init(argc, argv, "listener");
  ros::NodeHandle n;

  ros::Subscriber sub = n.subscribe("head/kinect2/bodyArray", 1000, bodies_sub_cb);


    ros::spin();

  return 0;
}

/*************************************************************************************
 Copyright (c) 2013, Carnegie Mellon University
 All rights reserved.
 Authors: Anurag Jakhotia<ajakhoti@andrew.cmu.edu>, Prasanna Velagapudi<pkv@cs.cmu.edu>
 Redistribution and use in source and binary forms, with or without modification, are
 permitted provided that the following conditions are met:
 -    Redistributions of source code must retain the above copyright notice, this list
 of conditions and the following disclaimer.
 -    Redistributions in binary form must reproduce the above copyright notice, this
 list of conditions and the following disclaimer in the documentation and/or other
 materials provided with the     distribution.
 -    Neither the name of Carnegie Mellon University nor the names of its contributors
 may be used to endorse or promote products derived from this software without
 specific prior written     permission.
 
 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
 EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT
 SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
 TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
 BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY
 WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 ***************************************************************************************//*************************************************************************************
                                                                                          Copyright (c) 2013, Carnegie Mellon University
                                                                                          All rights reserved.
                                                                                          Authors: Anurag Jakhotia<ajakhoti@andrew.cmu.edu>, Prasanna Velagapudi<pkv@cs.cmu.edu>
                                                                                          Redistribution and use in source and binary forms, with or without modification, are
                                                                                          permitted provided that the following conditions are met:
                                                                                          -    Redistributions of source code must retain the above copyright notice, this list
                                                                                          of conditions and the following disclaimer.
                                                                                          -    Redistributions in binary form must reproduce the above copyright notice, this
                                                                                          list of conditions and the following disclaimer in the documentation and/or other
                                                                                          materials provided with the     distribution.
                                                                                          -    Neither the name of Carnegie Mellon University nor the names of its contributors
                                                                                          may be used to endorse or promote products derived from this software without
                                                                                          specific prior written     permission.
                                                                                          
                                                                                          THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY 
                                                                                          EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES 
                                                                                          OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT 
                                                                                          SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, 
                                                                                          INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED 
                                                                                          TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR 
                                                                                          BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN 
                                                                                          CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY 
                                                                                          WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
                                                                                          ***************************************************************************************//*************************************************************************************
                                                                                                                                                                                   Copyright (c) 2013, Carnegie Mellon University
                                                                                                                                                                                   All rights reserved.
                                                                                                                                                                                   Authors: Anurag Jakhotia<ajakhoti@andrew.cmu.edu>, Prasanna Velagapudi<pkv@cs.cmu.edu>
                                                                                                                                                                                   Redistribution and use in source and binary forms, with or without modification, are
                                                                                                                                                                                   permitted provided that the following conditions are met:
                                                                                                                                                                                   -    Redistributions of source code must retain the above copyright notice, this list
                                                                                                                                                                                   of conditions and the following disclaimer.
                                                                                                                                                                                   -    Redistributions in binary form must reproduce the above copyright notice, this
                                                                                                                                                                                   list of conditions and the following disclaimer in the documentation and/or other 
                                                                                                                                                                                   materials provided with the     distribution.
                                                                                                                                                                                   -    Neither the name of Carnegie Mellon University nor the names of its contributors 
                                                                                                                                                                                   may be used to endorse or promote products derived from this software without 
                                                                                                                                                                                   specific prior written     permission.
                                                                                                                                                                                   
                                                                                                                                                                                   THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY 
                                                                                                                                                                                   EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES 
                                                                                                                                                                                   OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT 
                                                                                                                                                                                   SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, 
                                                                                                                                                                                   INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED 
                                                                                                                                                                                   TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR 
                                                                                                                                                                                   BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN 
                                                                                                                                                                                   CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY 
                                                                                                                                                                                   WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
                                                                                                                                                                                   ***************************************************************************************//*************************************************************************************
                                                                                                                                                                                                                                                                            Copyright (c) 2013, Carnegie Mellon University
                                                                                                                                                                                                                                                                            All rights reserved.
                                                                                                                                                                                                                                                                            Authors: Anurag Jakhotia<ajakhoti@andrew.cmu.edu>, Prasanna Velagapudi<pkv@cs.cmu.edu>
                                                                                                                                                                                                                                                                            Redistribution and use in source and binary forms, with or without modification, are
                                                                                                                                                                                                                                                                            permitted provided that the following conditions are met:
                                                                                                                                                                                                                                                                            -    Redistributions of source code must retain the above copyright notice, this list
                                                                                                                                                                                                                                                                            of conditions and the following disclaimer.
                                                                                                                                                                                                                                                                            -    Redistributions in binary form must reproduce the above copyright notice, this 
                                                                                                                                                                                                                                                                            list of conditions and the following disclaimer in the documentation and/or other 
                                                                                                                                                                                                                                                                            materials provided with the     distribution.
                                                                                                                                                                                                                                                                            -    Neither the name of Carnegie Mellon University nor the names of its contributors 
                                                                                                                                                                                                                                                                            may be used to endorse or promote products derived from this software without 
                                                                                                                                                                                                                                                                            specific prior written     permission.
                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                            THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY 
                                                                                                                                                                                                                                                                            EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES 
                                                                                                                                                                                                                                                                            OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT 
                                                                                                                                                                                                                                                                            SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, 
                                                                                                                                                                                                                                                                            INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED 
                                                                                                                                                                                                                                                                            TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR 
                                                                                                                                                                                                                                                                            BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN 
                                                                                                                                                                                                                                                                            CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY 
                                                                                                                                                                                                                                                                            WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
                                                                                                                                                                                                                                                                            ***************************************************************************************//*************************************************************************************
                                                                                                                                                                                                                                                                                                                                                                     Copyright (c) 2013, Carnegie Mellon University
                                                                                                                                                                                                                                                                                                                                                                     All rights reserved.
                                                                                                                                                                                                                                                                                                                                                                     Authors: Anurag Jakhotia<ajakhoti@andrew.cmu.edu>, Prasanna Velagapudi<pkv@cs.cmu.edu>
                                                                                                                                                                                                                                                                                                                                                                     Redistribution and use in source and binary forms, with or without modification, are
                                                                                                                                                                                                                                                                                                                                                                     permitted provided that the following conditions are met:
                                                                                                                                                                                                                                                                                                                                                                     -    Redistributions of source code must retain the above copyright notice, this list 
                                                                                                                                                                                                                                                                                                                                                                     of conditions and the following disclaimer.
                                                                                                                                                                                                                                                                                                                                                                     -    Redistributions in binary form must reproduce the above copyright notice, this 
                                                                                                                                                                                                                                                                                                                                                                     list of conditions and the following disclaimer in the documentation and/or other 
                                                                                                                                                                                                                                                                                                                                                                     materials provided with the     distribution.
                                                                                                                                                                                                                                                                                                                                                                     -    Neither the name of Carnegie Mellon University nor the names of its contributors 
                                                                                                                                                                                                                                                                                                                                                                     may be used to endorse or promote products derived from this software without 
                                                                                                                                                                                                                                                                                                                                                                     specific prior written     permission.
                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY 
                                                                                                                                                                                                                                                                                                                                                                     EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES 
                                                                                                                                                                                                                                                                                                                                                                     OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT 
                                                                                                                                                                                                                                                                                                                                                                     SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, 
                                                                                                                                                                                                                                                                                                                                                                     INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED 
                                                                                                                                                                                                                                                                                                                                                                     TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR 
                                                                                                                                                                                                                                                                                                                                                                     BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN 
                                                                                                                                                                                                                                                                                                                                                                     CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY 
                                                                                                                                                                                                                                                                                                                                                                     WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
                                                                                                                                                                                                                                                                                                                                                                     ***************************************************************************************//*************************************************************************************
                                                                                                                                                                                                                                                                                                                                                                                                                                                              Copyright (c) 2013, Carnegie Mellon University
                                                                                                                                                                                                                                                                                                                                                                                                                                                              All rights reserved.
                                                                                                                                                                                                                                                                                                                                                                                                                                                              Authors: Anurag Jakhotia<ajakhoti@andrew.cmu.edu>, Prasanna Velagapudi<pkv@cs.cmu.edu>
                                                                                                                                                                                                                                                                                                                                                                                                                                                              Redistribution and use in source and binary forms, with or without modification, are
                                                                                                                                                                                                                                                                                                                                                                                                                                                              permitted provided that the following conditions are met:
                                                                                                                                                                                                                                                                                                                                                                                                                                                              -    Redistributions of source code must retain the above copyright notice, this list 
                                                                                                                                                                                                                                                                                                                                                                                                                                                              of conditions and the following disclaimer.
                                                                                                                                                                                                                                                                                                                                                                                                                                                              -    Redistributions in binary form must reproduce the above copyright notice, this 
                                                                                                                                                                                                                                                                                                                                                                                                                                                              list of conditions and the following disclaimer in the documentation and/or other 
                                                                                                                                                                                                                                                                                                                                                                                                                                                              materials provided with the     distribution.
                                                                                                                                                                                                                                                                                                                                                                                                                                                              -    Neither the name of Carnegie Mellon University nor the names of its contributors 
                                                                                                                                                                                                                                                                                                                                                                                                                                                              may be used to endorse or promote products derived from this software without 
                                                                                                                                                                                                                                                                                                                                                                                                                                                              specific prior written     permission.
                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                              THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY 
                                                                                                                                                                                                                                                                                                                                                                                                                                                              EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES 
                                                                                                                                                                                                                                                                                                                                                                                                                                                              OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT 
                                                                                                                                                                                                                                                                                                                                                                                                                                                              SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                              INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED 
                                                                                                                                                                                                                                                                                                                                                                                                                                                              TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR 
                                                                                                                                                                                                                                                                                                                                                                                                                                                              BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN 
                                                                                                                                                                                                                                                                                                                                                                                                                                                              CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY 
                                                                                                                                                                                                                                                                                                                                                                                                                                                              WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
                                                                                                                                                                                                                                                                                                                                                                                                                                                              ***************************************************************************************//*************************************************************************************
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       Copyright (c) 2013, Carnegie Mellon University
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       All rights reserved.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       Authors: Anurag Jakhotia<ajakhoti@andrew.cmu.edu>, Prasanna Velagapudi<pkv@cs.cmu.edu>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       Redistribution and use in source and binary forms, with or without modification, are 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       permitted provided that the following conditions are met:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       -    Redistributions of source code must retain the above copyright notice, this list 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       of conditions and the following disclaimer.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       -    Redistributions in binary form must reproduce the above copyright notice, this 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       list of conditions and the following disclaimer in the documentation and/or other 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       materials provided with the     distribution.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       -    Neither the name of Carnegie Mellon University nor the names of its contributors 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       may be used to endorse or promote products derived from this software without 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       specific prior written     permission.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       ***************************************************************************************//*************************************************************************************
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Copyright (c) 2013, Carnegie Mellon University
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                All rights reserved.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Authors: Anurag Jakhotia<ajakhoti@andrew.cmu.edu>, Prasanna Velagapudi<pkv@cs.cmu.edu>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Redistribution and use in source and binary forms, with or without modification, are 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                permitted provided that the following conditions are met:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                -    Redistributions of source code must retain the above copyright notice, this list 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                of conditions and the following disclaimer.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                -    Redistributions in binary form must reproduce the above copyright notice, this 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                list of conditions and the following disclaimer in the documentation and/or other 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                materials provided with the     distribution.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                -    Neither the name of Carnegie Mellon University nor the names of its contributors 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                may be used to endorse or promote products derived from this software without 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                specific prior written     permission.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ***************************************************************************************//*************************************************************************************
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         Copyright (c) 2013, Carnegie Mellon University
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         All rights reserved.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         Authors: Anurag Jakhotia<ajakhoti@andrew.cmu.edu>, Prasanna Velagapudi<pkv@cs.cmu.edu>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         Redistribution and use in source and binary forms, with or without modification, are 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         permitted provided that the following conditions are met:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         -    Redistributions of source code must retain the above copyright notice, this list 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         of conditions and the following disclaimer.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         -    Redistributions in binary form must reproduce the above copyright notice, this 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         list of conditions and the following disclaimer in the documentation and/or other 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         materials provided with the     distribution.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         -    Neither the name of Carnegie Mellon University nor the names of its contributors 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         may be used to endorse or promote products derived from this software without 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         specific prior written     permission.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ***************************************************************************************/
